name: base
channels:
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - anaconda-anon-usage=0.5.0=py312hfc0e8ea_100
  - annotated-types=0.6.0=py312h06a4308_0
  - anyio=4.10.0=py312h06a4308_0
  - archspec=0.2.3=pyhd3eb1b0_0
  - asttokens=3.0.0=pyhd8ed1ab_1
  - boltons=24.1.0=py312h06a4308_0
  - brotli-python=1.0.9=py312h6a678d5_9
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.19.1=h5eee18b_0
  - ca-certificates=2025.12.2=h06a4308_0
  - certifi=2026.01.04=py312h06a4308_0
  - cffi=1.17.1=py312h1fdaa30_1
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - comm=0.2.2=pyhd8ed1ab_1
  - conda=25.1.1=py312h06a4308_0
  - conda-anaconda-telemetry=0.1.2=py312h06a4308_0
  - conda-anaconda-tos=0.1.2=py312h06a4308_0
  - conda-content-trust=0.2.0=py312h06a4308_1
  - conda-libmamba-solver=25.1.1=pyhd3eb1b0_0
  - conda-package-handling=2.4.0=py312h06a4308_0
  - conda-package-streaming=0.11.0=py312h06a4308_0
  - cpp-expected=1.1.0=hdb19cb5_0
  - cryptography=43.0.3=py312h7825ff9_1
  - datasets=4.4.1=py312h06a4308_1
  - debugpy=1.8.11=py312h6a678d5_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - distro=1.9.0=py312h06a4308_0
  - exceptiongroup=1.2.2=pyhd8ed1ab_1
  - executing=2.1.0=pyhd8ed1ab_1
  - expat=2.6.4=h6a678d5_0
  - fmt=9.1.0=hdb19cb5_1
  - frozendict=2.4.2=py312h06a4308_0
  - h11=0.16.0=py312h06a4308_1
  - hf-xet=1.1.8=py312h84c0859_0
  - httpcore=1.0.9=py312h06a4308_0
  - httpx=0.28.1=py312h06a4308_1
  - huggingface_hub=0.34.4=py312h06a4308_0
  - icu=73.1=h6a678d5_0
  - idna=3.7=py312h06a4308_0
  - ijson=3.4.0.post0=py312hee96239_0
  - importlib-metadata=8.6.1=pyha770c72_0
  - ipykernel=6.29.5=pyh3099207_0
  - ipython=9.1.0=pyhfb0248b_0
  - ipython_pygments_lexers=1.1.1=pyhd8ed1ab_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - jsonpatch=1.33=py312h06a4308_1
  - jsonpointer=2.1=pyhd3eb1b0_0
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.7.2=pyh31011fe_1
  - krb5=1.20.1=h143b758_1
  - ld_impl_linux-64=2.40=h12ee557_0
  - libarchive=3.7.7=hfab0078_0
  - libcurl=8.11.1=hc9e6f67_0
  - libedit=3.1.20230828=h5eee18b_0
  - libev=4.33=h7f8727e_1
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libmamba=2.0.5=haf1ee3a_1
  - libmambapy=2.0.5=py312hdb19cb5_1
  - libnghttp2=1.57.0=h2d74bed_0
  - libsodium=1.0.18=h36c2ea0_1
  - libsolv=0.7.30=he621ea3_1
  - libssh2=1.11.1=h251f7ec_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - libxml2=2.13.5=hfdd30dd_0
  - lz4-c=1.9.4=h6a678d5_1
  - markdown-it-py=2.2.0=py312h06a4308_1
  - matplotlib-inline=0.1.7=pyhd8ed1ab_1
  - mdurl=0.1.0=py312h06a4308_0
  - menuinst=2.2.0=py312h06a4308_1
  - ncurses=6.4=h6a678d5_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - nlohmann_json=3.11.2=h6a678d5_0
  - openssl=3.0.18=hd6dcaed_0
  - packaging=24.2=py312h06a4308_0
  - parso=0.8.4=pyhd8ed1ab_1
  - pcre2=10.42=hebb0a14_1
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pip=25.0=py312h06a4308_0
  - platformdirs=3.10.0=py312h06a4308_0
  - pluggy=1.5.0=py312h06a4308_0
  - prompt-toolkit=3.0.51=pyha770c72_0
  - psutil=5.9.0=py312h5eee18b_1
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pybind11-abi=5=hd3eb1b0_0
  - pycosat=0.6.6=py312h5eee18b_2
  - pycparser=2.21=pyhd3eb1b0_0
  - pydantic=2.10.3=py312h06a4308_0
  - pydantic-core=2.27.1=py312h4aa5aa6_0
  - pygments=2.15.1=py312h06a4308_1
  - pysocks=1.7.1=py312h06a4308_0
  - python=3.12.9=h5148396_0
  - python-dateutil=2.9.0.post0=pyhff2d567_1
  - python-xxhash=3.5.0=py312h5eee18b_0
  - pyzmq=26.2.0=py312h6a678d5_0
  - readline=8.2=h5eee18b_0
  - reproc=14.2.4=h6a678d5_2
  - reproc-cpp=14.2.4=h6a678d5_2
  - requests=2.32.3=py312h06a4308_1
  - rich=13.9.4=py312h06a4308_0
  - ruamel.yaml=0.18.6=py312h5eee18b_0
  - ruamel.yaml.clib=0.2.8=py312h5eee18b_0
  - setuptools=75.8.0=py312h06a4308_0
  - simdjson=3.10.1=hdb19cb5_0
  - six=1.17.0=pyhd8ed1ab_0
  - sniffio=1.3.1=py312h06a4308_0
  - spdlog=1.11.0=hdb19cb5_0
  - sqlite=3.45.3=h5eee18b_0
  - stack_data=0.6.3=pyhd8ed1ab_1
  - tk=8.6.14=h39e8969_0
  - tornado=6.4.2=py312h5eee18b_0
  - tqdm=4.67.1=py312h7040dfc_1
  - traitlets=5.14.3=pyhd8ed1ab_1
  - truststore=0.10.0=py312h06a4308_0
  - typing-extensions=4.12.2=py312h06a4308_0
  - typing_extensions=4.12.2=py312h06a4308_0
  - urllib3=2.3.0=py312h06a4308_0
  - wcwidth=0.2.13=pyhd8ed1ab_1
  - wheel=0.45.1=py312h06a4308_0
  - xxhash=0.8.0=h7f8727e_3
  - xz=5.4.6=h5eee18b_1
  - yajl=2.1.0=h7f8727e_1
  - yaml-cpp=0.8.0=h6a678d5_1
  - zeromq=4.3.5=h6a678d5_0
  - zipp=3.21.0=pyhd8ed1ab_1
  - zlib=1.2.13=h5eee18b_1
  - zstandard=0.23.0=py312h2c38b39_1
  - zstd=1.5.6=hc292b87_0
  - pip:
      - absl-py==2.2.2
      - accelerate==1.6.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.12.15
      - aiosignal==1.4.0
      - argparse==1.4.0
      - attrs==25.3.0
      - click==8.2.1
      - cloudpickle==3.1.1
      - contourpy==1.3.2
      - cycler==0.12.1
      - dill==0.3.8
      - filelock==3.13.1
      - fonttools==4.57.0
      - frozenlist==1.7.0
      - fsspec==2024.6.1
      - gitdb==4.0.12
      - gitpython==3.1.45
      - grpcio==1.71.0
      - gym==0.26.2
      - gym-notices==0.0.8
      - huggingface-hub==0.30.2
      - jinja2==3.1.4
      - kiwisolver==1.4.8
      - markdown==3.8
      - markupsafe==2.1.5
      - matplotlib==3.10.1
      - mpmath==1.3.0
      - multidict==6.6.4
      - multiprocess==0.70.16
      - networkx==3.3
      - numpy==2.1.2
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.1.105
      - nvidia-nvtx-cu12==12.1.105
      - pandas==2.3.2
      - pathlib==1.0.1
      - pillow==11.0.0
      - propcache==0.3.2
      - protobuf==6.30.2
      - pyarrow==21.0.0
      - pyparsing==3.2.3
      - pytz==2025.2
      - pyyaml==6.0.2
      - regex==2024.11.6
      - safetensors==0.5.3
      - sentencepiece==0.2.1
      - sentry-sdk==2.35.0
      - smmap==5.0.2
      - sympy==1.13.1
      - tensorboard==2.19.0
      - tensorboard-data-server==0.7.2
      - tokenizers==0.21.1
      - torch==2.5.1+cu121
      - torch-tb-profiler==0.4.3
      - torchaudio==2.5.1+cu121
      - torchsummary==1.5.1
      - torchvision==0.20.1+cu121
      - transformers==4.51.3
      - triton==3.1.0
      - tzdata==2025.2
      - wandb==0.21.1
      - werkzeug==3.1.3
      - yarl==1.20.1
prefix: /root/miniconda3
